### ISSUE TITLE
JSON parsing issue in #data

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/generic-extractor#70] opened 2017-06-06 11:47 UTC
Just blindly tried running Bearer Auth example - https://developers.keboola.com/extend/generic-extractor/configuration/api/authentication/oauth20/#bearer-authentication

Added a dummy `config` part, so the config looks like

```json
{
    "parameters": {
        "api": {
            "baseUrl": "https://example.com/",
            "authentication": {
                "type": "oauth20",
                "format": "json",
                "headers": {
                    "Authorization": {
                        "function": "concat",
                        "args": [
                            "Bearer ",
                            {
                                "authorization": "data"
                            }
                        ]
                    }
                }
            }
        },
        "config": {
            "outputBucket": "mydata",
            "jobs": [
                {
                    "endpoint": "endpoint"
                }
            ]
        }
    },
    "authorization": {
        "oauth_api": {
            "credentials": {
                "#data": "SomeToken1234abcd567ef",
                "appKey": "clientId",
                "#appSecret": "clientSecret"
            }
        }
    }
}
```

and the result is application error with this stack trace

```
JSON decode error: Syntax error, malformed JSON 
{
    "errFile": "/home/vendor/keboola/php-utils/src/Keboola/Utils/Utils.php",
    "errLine": 53,
    "trace": [
        {
            "file": "/home/src/Keboola/GenericExtractor/Authentication/OAuth20.php",
            "line": 79,
            "function": "json_decode",
            "class": "Keboola\\Utils\\Utils",
            "type": "::",
            "args": [
                "SomeToken1234abcd567ef"
            ]
        },
        {
            "file": "/home/src/Keboola/GenericExtractor/Config/Api.php",
            "line": 143,
            "function": "__construct",
            "class": "Keboola\\GenericExtractor\\Authentication\\OAuth20",
            "type": "->",
            "args": [
                {
                    "oauth_api": {
                        "credentials": {
                            "#data": "SomeToken1234abcd567ef",
                            "appKey": "clientId",
                            "#appSecret": "clientSecret"
                        }
                    }
                },
                {
                    "type": "oauth20",
                    "format": "json",
                    "headers": {
                        "Authorization": {
                            "function": "concat",
                            "args": [
                                "Bearer ",
                                {
                                    "authorization": "data"
                                }
                            ]
                        }
                    }
                },
                "[object] (Keboola\\Code\\Builder: {})"
            ]
        },
        {
            "file": "/home/src/Keboola/GenericExtractor/Config/Api.php",
            "line": 86,
            "function": "createAuth",
            "class": "Keboola\\GenericExtractor\\Config\\Api",
            "type": "::",
            "args": [
                {
                    "baseUrl": "https://example.com/",
                    "authentication": {
                        "type": "oauth20",
                        "format": "json",
                        "headers": {
                            "Authorization": {
                                "function": "concat",
                                "args": [
                                    "Bearer ",
                                    {
                                        "authorization": "data"
                                    }
                                ]
                            }
                        }
                    }
                },
                "[object] (Keboola\\Juicer\\Config\\Config: {})",
                {
                    "oauth_api": {
                        "credentials": {
                            "#data": "SomeToken1234abcd567ef",
                            "appKey": "clientId",
                            "#appSecret": "clientSecret"
                        }
                    }
                }
            ]
        },
        {
            "file": "/home/src/Keboola/GenericExtractor/Config/Configuration.php",
            "line": 47,
            "function": "create",
            "class": "Keboola\\GenericExtractor\\Config\\Api",
            "type": "::",
            "args": [
                {
                    "baseUrl": "https://example.com/",
                    "authentication": {
                        "type": "oauth20",
                        "format": "json",
                        "headers": {
                            "Authorization": {
                                "function": "concat",
                                "args": [
                                    "Bearer ",
                                    {
                                        "authorization": "data"
                                    }
                                ]
                            }
                        }
                    }
                },
                "[object] (Keboola\\Juicer\\Config\\Config: {})",
                {
                    "oauth_api": {
                        "credentials": {
                            "#data": "SomeToken1234abcd567ef",
                            "appKey": "clientId",
                            "#appSecret": "clientSecret"
                        }
                    }
                }
            ]
        },
        {
            "file": "/home/src/Keboola/GenericExtractor/Executor.php",
            "line": 69,
            "function": "getApi",
            "class": "Keboola\\GenericExtractor\\Config\\Configuration",
            "type": "->",
            "args": [
                "[object] (Keboola\\Juicer\\Config\\Config: {})",
                {
                    "oauth_api": {
                        "credentials": {
                            "#data": "SomeToken1234abcd567ef",
                            "appKey": "clientId",
                            "#appSecret": "clientSecret"
                        }
                    }
                }
            ]
        },
        {
            "file": "/home/run.php",
            "line": 19,
            "function": "run",
            "class": "Keboola\\GenericExtractor\\Executor",
            "type": "->",
            "args": []
        }
    ],
    "exception": "Keboola\\Utils\\Exception\\JsonDecodeException"
}

```

**Comment by odinuv** [comment] 2017-06-13 07:47
when `authentication.format` is `json`, then `#data` is expected to be json -> not a bug

fixed in https://github.com/keboola/developers-docs/commit/1f5a2b2d1a82b3b9090dd986f84477a72ed8bc88

**Closed by odinuv** 2017-06-13 07:47 UTC
Labels: bug
